// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpeejxsrwhoevncjuaov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwZWVqeHNyd2hvZXZuY2p1YW92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MDA5ODUsImV4cCI6MjA2NzM3Njk4NX0.DzvQ1nnFabG5zHQKUpldACBiRbWBvaQ3Ge7P4AWzhc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});